# Generated by Django 4.2.5 on 2024-04-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
