# Generated by Django 4.2.8 on 2024-05-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user_name',
            field=models.CharField(default='xx', max_length=100),
        ),
    ]
